# Generated by Django 5.0.7 on 2024-08-11 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Business', 'Business'), ('Academy', 'Academy'), ('Others', 'Others')], max_length=10)),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('notes', models.TextField(blank=True, max_length=300, null=True, verbose_name='Notes')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_city', to='settings.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_country', to='settings.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserAddress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Business', 'Business'), ('Academy', 'Academy'), ('Others', 'Others')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserPhone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
