# Generated by Django 5.0.7 on 2024-08-12 11:56

import utils.generate_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraddress_user_alter_userphonenumber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default=utils.generate_code.generate_code, max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='code_used',
            field=models.BooleanField(default=False),
        ),
    ]
