# Generated by Django 5.0.7 on 2024-09-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_code_profile_code_used'),
        ('products', '0013_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite_product', to='products.product'),
        ),
    ]
