# Generated by Django 5.0.7 on 2024-08-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_city_options_alter_country_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('logo', models.ImageField(upload_to='company/', verbose_name='Logo')),
                ('about', models.CharField(max_length=300, verbose_name='About')),
                ('fb_link', models.URLField(blank=True, null=True, verbose_name='Facebook Link')),
                ('tw_link', models.URLField(blank=True, null=True, verbose_name='Twitter Link')),
                ('ins_link', models.URLField(blank=True, null=True, verbose_name='Instagram Link')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
            ],
        ),
    ]
