# Generated by Django 5.0.7 on 2024-09-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=400, verbose_name='Sub-title')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Image')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
        ),
    ]
