# Generated by Django 5.0.7 on 2024-09-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cartorder_cartdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
