# Generated by Django 5.0.7 on 2024-09-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cartdetail_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
        ),
    ]
