# Generated by Django 5.0.7 on 2024-09-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_cartdetail_price_alter_cartdetail_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='order_time',
        ),
    ]
