# Generated by Django 5.0.7 on 2024-08-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='', upload_to='brand/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
