# Generated by Django 5.0.7 on 2024-08-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='products/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
